name: Deploy Develop to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. SSH 키 설정
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # 3. EC2 서버에 배포 스크립트 실행
      - name: Deploy to EC2
        env:
          PROJECT_NAME: k-laci-backend
          DEPLOY_DIR: /home/ec2-user/k-laci-backend
          BRANCH: develop
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd $DEPLOY_DIR
          git pull origin $BRANCH
          cd packages/backend
          yarn install --frozen-lockfile
          yarn build
          pm2 restart $PROJECT_NAME || pm2 start dist/main.js --name $PROJECT_NAME
          EOF 